// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chat-variants/DealRoom.tsx": () => import("../components/mockups/chat-variants/DealRoom.tsx"),
  "./components/mockups/chat-variants/DealStatus.tsx": () => import("../components/mockups/chat-variants/DealStatus.tsx"),
  "./components/mockups/chat-variants/OfferCard.tsx": () => import("../components/mockups/chat-variants/OfferCard.tsx"),
  "./components/mockups/combined/FullHome.tsx": () => import("../components/mockups/combined/FullHome.tsx"),
  "./components/mockups/messages-tab/LayoutA.tsx": () => import("../components/mockups/messages-tab/LayoutA.tsx"),
  "./components/mockups/messages-tab/LayoutB.tsx": () => import("../components/mockups/messages-tab/LayoutB.tsx"),
  "./components/mockups/messages-tab/LayoutC.tsx": () => import("../components/mockups/messages-tab/LayoutC.tsx"),
  "./components/mockups/messaging-models/ModelA_ChatFirst.tsx": () => import("../components/mockups/messaging-models/ModelA_ChatFirst.tsx"),
  "./components/mockups/messaging-models/ModelB_OfferFirst.tsx": () => import("../components/mockups/messaging-models/ModelB_OfferFirst.tsx"),
  "./components/mockups/messaging-models/ModelC_OneThreadPerWant.tsx": () => import("../components/mockups/messaging-models/ModelC_OneThreadPerWant.tsx"),
  "./components/mockups/messaging-models/ModelD_InboxStatus.tsx": () => import("../components/mockups/messaging-models/ModelD_InboxStatus.tsx"),
  "./components/mockups/offers-sent/BoldModern.tsx": () => import("../components/mockups/offers-sent/BoldModern.tsx"),
  "./components/mockups/offers-sent/DarkCommand.tsx": () => import("../components/mockups/offers-sent/DarkCommand.tsx"),
  "./components/mockups/offers-sent/MinimalEditorial.tsx": () => import("../components/mockups/offers-sent/MinimalEditorial.tsx"),
  "./components/mockups/offers-sent/WarmMarketplace.tsx": () => import("../components/mockups/offers-sent/WarmMarketplace.tsx"),
  "./components/mockups/tab-bar-variants/ExpandingLabel.tsx": () => import("../components/mockups/tab-bar-variants/ExpandingLabel.tsx"),
  "./components/mockups/tab-bar-variants/FloatingPill.tsx": () => import("../components/mockups/tab-bar-variants/FloatingPill.tsx"),
  "./components/mockups/tab-bar-variants/Glassmorphic.tsx": () => import("../components/mockups/tab-bar-variants/Glassmorphic.tsx"),
  "./components/mockups/want-card-variants/DesireForward.tsx": () => import("../components/mockups/want-card-variants/DesireForward.tsx"),
  "./components/mockups/want-card-variants/OfferLed.tsx": () => import("../components/mockups/want-card-variants/OfferLed.tsx"),
  "./components/mockups/want-card-variants/SocialUrgency.tsx": () => import("../components/mockups/want-card-variants/SocialUrgency.tsx"),
  "./components/mockups/want-cards/MarketplaceListing.tsx": () => import("../components/mockups/want-cards/MarketplaceListing.tsx"),
  "./components/mockups/want-cards/OfferLed.tsx": () => import("../components/mockups/want-cards/OfferLed.tsx"),
  "./components/mockups/want-cards/PhotoForward.tsx": () => import("../components/mockups/want-cards/PhotoForward.tsx"),
  "./components/mockups/want-cards/SocialFeed.tsx": () => import("../components/mockups/want-cards/SocialFeed.tsx")
};
