// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/messaging-models/ModelA_ChatFirst.tsx": () => import("../components/mockups/messaging-models/ModelA_ChatFirst.tsx"),
  "./components/mockups/messaging-models/ModelB_OfferFirst.tsx": () => import("../components/mockups/messaging-models/ModelB_OfferFirst.tsx"),
  "./components/mockups/messaging-models/ModelC_OneThreadPerWant.tsx": () => import("../components/mockups/messaging-models/ModelC_OneThreadPerWant.tsx"),
  "./components/mockups/messaging-models/ModelD_InboxStatus.tsx": () => import("../components/mockups/messaging-models/ModelD_InboxStatus.tsx"),
  "./components/mockups/want-cards/MarketplaceListing.tsx": () => import("../components/mockups/want-cards/MarketplaceListing.tsx"),
  "./components/mockups/want-cards/OfferLed.tsx": () => import("../components/mockups/want-cards/OfferLed.tsx"),
  "./components/mockups/want-cards/PhotoForward.tsx": () => import("../components/mockups/want-cards/PhotoForward.tsx"),
  "./components/mockups/want-cards/SocialFeed.tsx": () => import("../components/mockups/want-cards/SocialFeed.tsx"),
  "./components/mockups/offers-sent/BoldModern.tsx": () => import("../components/mockups/offers-sent/BoldModern.tsx"),
  "./components/mockups/offers-sent/DarkCommand.tsx": () => import("../components/mockups/offers-sent/DarkCommand.tsx"),
  "./components/mockups/offers-sent/MinimalEditorial.tsx": () => import("../components/mockups/offers-sent/MinimalEditorial.tsx"),
  "./components/mockups/offers-sent/WarmMarketplace.tsx": () => import("../components/mockups/offers-sent/WarmMarketplace.tsx")
};
